spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/markethub
spring.datasource.username=root
spring.datasource.password=Truptir@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=admin
spring.security.user.password=admin
